### ISSUE TITLE
Backup function issue

### ISSUE THREAD

**Issue by jfburr** [JulesLeCurly/CryptoGame#1]
<img width="726" alt="Capture d’écran 2023-01-18 à 22 11 38" src="https://user-images.githubusercontent.com/12183814/213295712-db2853a4-2387-4810-9a69-04b22b1fd427.png">

**Comment by JulesLeCurly** [comment]
OK C EST COOL MAIS C EST FAUX§§§§§§§§§§§§§§§§§§§§§§§§§§§
